### ISSUE TITLE
Registrieren: ungültige Postleitzahl provoziert in Address-Constructor IllegalArgumentException

### ISSUE THREAD

**Issue by hessg1** [joshuadrewlow/ch.bfh.btx8081.w2017.orange#8]
Sollte man die abfangen und im GUI aufbereiten?

**Comment by engeld** [comment]
Kann ich sonst easy im Rahmen von Issue #6 machen? :)

**Comment by engeld** [comment]
Also: Im LoginPresenter die IllegalArgumentException bezüglich invalider ZIP abfangen und dem User dies als Notification anzeigen

**Comment by engeld** [comment]
Wurde ein bisschen anders gelöst:
Die eingegebene ZIP wird darauf geprüft, ob sie numerisch ist und ob sie vierstellig ist.
